---
title: "Supplementary materials"
author: "Gerardo Martín"
date: "2023-02-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Land cover

```{r echo=F, fig.height=5, fig.width=4, fig.cap="Land cover base layer upon which land cover predictions were generated. 6 = Tea, 5 = Urban, 4 = Agricultural, 3 = Degraded forest, 2 = Forest, 1 = Water.", fig.align='center', message=FALSE, warning=FALSE}
lc <- readRDS("Data-objects/Snakes-env-data.rds")
library(raster)
lc.r <- rasterFromXYZ(lc[, c("x", "y", "land.cover")])
plot(lc.r)
```

\newpage

## Tree cover

```{r echo=F, fig.height=5, fig.width=4, fig.cap="Base tree cover layer used for generating tree cover predictions.", fig.align='center'}
tc.r <- rasterFromXYZ(lc[, c("x", "y", "tree")])
plot(tc.r)
```

\newpage


## Human population density

```{r echo=F, fig.align='center', fig.cap="Human population density of 2010 at 1 km.", fig.height=6, fig.width=4, message=F, warning=F}
popn <- raster("pop_2010.asc")
plot(popn)
```

\newpage

## Digital elevation model

```{r dem, echo=F, fig.height=6, fig.width=4, message=FALSE, warning=FALSE, fig.align='center', fig.cap="Digital elevation model of Sri Lanka at 1 km."}
dem <- raster("LKA-dem-WGS84-1km.tif")
dem <- projectRaster(dem, crs = CRS(proj4string(popn)))
plot(dem)
```

\newpage

## Snake distributions

```{r echo = F}
sn.files <- list.files("Snakes", "tif", recursive = T, full.names = T)
df.files.1 <- expand.grid(species = c("B. caeruleus", "B. ceylonicus", "D. russelli", "E. carinatus", "H. spp", "N. naja", "T. trigonocephalus"), year = 2010:2050, GCM = c(""), ssp = c("SSP1"))
df.files.25 <- expand.grid(species = c("B. caeruleus", "B. ceylonicus", "D. russelli", "E. carinatus", "H. spp", "N. naja", "T. trigonocephalus"), year = 2010:2050, GCM = c("CNRM-CM5", "GFDL-CM3", "MPI-ESM-LR"), ssp = c("SSP2", "SSP5"))

df.files <- rbind(df.files.1, df.files.25)

id.ssp1 <- which(df.files$ssp == "SSP1" & df.files$year %in% c(2010, 2024, 2037, 2050))
id.ssp2 <- which(df.files$ssp == "SSP2" & df.files$year %in% c(2010, 2024, 2037, 2050))
id.ssp5 <- which(df.files$ssp == "SSP5" & df.files$year %in% c(2010, 2024, 2037, 2050))

snakes.ssp1 <- lapply(sn.files[id.ssp1], raster)
snakes.ssp2 <- lapply(sn.files[id.ssp2], raster)
snakes.ssp5 <- lapply(sn.files[id.ssp5], raster)
```

### SSP1

```{r echo = F, fig.align='center', fig.cap="Snake suitability predictions for SSP1 in four time steps.", fig.width=12, fig.height=10}
par(mfrow = c(4, 7), bty = "n", mar = c(2,2,2,2))
for(i in seq_along(id.ssp1)){
    plot(snakes.ssp1[[i]], main = paste0(df.files$species[id.ssp1[i]],": ", 
                                         df.files$year[id.ssp1[i]], " (", 
                                         df.files$ssp[id.ssp1[i]], ", ",
                                         df.files$GCM[id.ssp1[i]], ")"),
         cex.main = 0.7,
         axes = F,
         axis = F,
         legend = F)
}
```

\newpage

### SSP2

```{r echo = F, fig.align='center', fig.cap="Snake suitability predictions for SSP2 in four time steps and three global circulation models.", fig.width=12, fig.height=10}
par(mfrow = c(4, 7), bty = "n", mar = c(2,2,2,2))
for(i in seq_along(id.ssp2)){
    plot(snakes.ssp2[[i]], main = paste0(df.files$species[id.ssp2[i]],": ", 
                                         df.files$year[id.ssp2[i]], " (", 
                                         df.files$ssp[id.ssp2[i]], ", ",
                                         df.files$GCM[id.ssp2[i]], ")"),
         cex.main = 0.7,
         axes = F,
         axis = F,
         legend = F)
}
```

\newpage

### SSP5

```{r echo = F, fig.align='center', fig.cap="Snake suitability predictions for SSP5 in four time steps and three global circulation models.", fig.width=12, fig.height=10}
par(mfrow = c(4, 7), bty = "n", mar = c(2,2,2,2))
for(i in seq_along(id.ssp5)){
    plot(snakes.ssp5[[i]], main = paste0(df.files$species[id.ssp5[i]],": ", 
                                         df.files$year[id.ssp5[i]], " (", 
                                         df.files$ssp[id.ssp5[i]], ", ",
                                         df.files$GCM[id.ssp5[i]], ")"),
         cex.main = 0.7,
         axes = F,
         axis = F,
         legend = F)
}
```

\newpage

## Human population predictions

```{r echo = F, fig.align='center', fig.cap="Population predictions for 2010-2050 in each shares socioeconomic pathway.", fig.width=6, fig.height=4}
pop.files <- list.files("Population-5km", "tif", full.names = T, recursive = T)
pop.preds <- stack(pop.files)
pop.preds.sum <- cellStats(pop.preds, sum)
scen <- expand.grid(year = 2010:2050, SSP = c("SSP1", "SSP2", "SSP5"))
scen$popn <- pop.preds.sum

library(ggplot2)

ggplot(scen) + geom_step(aes(x = year, y = popn, colour = SSP)) +
    geom_point(aes(x = year, y = popn, colour = SSP), size = 0.2)
```



